version: '2'
services:
  web:
    image: mon_projet_web
    build: .
    ports:
      - "80:80"
    depends_on:
      - postgres
      - elasticsearch
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: data
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

volumes:
  pg-data:


