version: '2'
services:
  web:
    image: mon_projet_web
    build: .
    ports:
      - "80:80"
    depends_on:
      - postgres
      - mongodb
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: data
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data
  mongodb:
    image: mongo:latest
    volumes:
    - mongo-data:/data/db

volumes:
  pg-data:
  mongo-data:

